addons:
  apt:
    packages:
        - expect-dev  # provides unbuffer utility
        - python-lxml # because pip installation is slow

language: python

python:
    - "2.7"

env:
    global:
    - VERSION="9.0" ODOO_REPO="odoo/odoo" EXCLUDE="account_reconcile_compassion,account_statement_completion_compassion"
    matrix:
    - LINT_CHECK="1"

virtualenv:
  system_site_packages: true

install:
    - pip install click flake8 coveralls xlrd pylint pylint_odoo coverage codecov
    # - pip install pysftp MySQL-python unidecode pysmb urllib3 certifi
    - git clone https://github.com/CompassionCH/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools -b r2
    - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
    # - git clone https://github.com/CompassionCH/compassion-modules.git ${HOME}/build/CompassionCH/compassion-modules -b 8.0
    # - git clone https://github.com/OCA/bank-statement-reconcile.git ${HOME}/build/CompassionCH/bank-statement-reconcile -b 9.0
    # - git clone https://github.com/OCA/bank-statement-import.git ${HOME}/build/CompassionCH/bank-statement-import -b 9.0
    # - git clone https://github.com/OCA/l10n-switzerland.git ${HOME}/build/CompassionCH/l10n-switzerland -b 9.0
    # - git clone https://github.com/OCA/web.git ${HOME}/build/CompassionCH/web -b 9.0
#    - git clone https://github.com/OCA/bank-payment.git ${HOME}/build/CompassionCH/bank-payment -b 9.0
#    - git clone https://github.com/OCA/account-financial-tools.git ${HOME}/build/CompassionCH/account-financial-tools -b 9.0
#    - git clone https://github.com/OCA/partner-contact.git ${HOME}/build/CompassionCH/partner-contact -b 9.0
    - git clone https://github.com/OCA/connector.git ${HOME}/build/CompassionCH/connector -b 9.0
#    - rm -rf ${HOME}/build/CompassionCH/compassion-modules/sbc_compassion
#    - rm -rf ${HOME}/build/CompassionCH/compassion-modules/onramp_compassion
    - travis_install_nightly

before_script:
    - touch ${HOME}/odoo-9.0/odoo.conf
  
script:
    - travis/travis_header.sh
    - travis_run_tests 


after_success:
    - travis_after_success
